openapi: 3.0.1
info:
  title: FeeStudent API
  description: API to support student fee collection
  version: ${project.version}

paths:
  '/student/{studentId}/fee:all':
    get:
      operationId: getAllFeesByStudentIdForTheYear
      summary: Return fees applicable for student
      parameters:
        - name: studentId
          in: path
          description: Unique StudentId i.e Roll-number
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StudentFeeDetails'

  '/student/{studentId}/fee:pending':
    get:
      operationId: getPendingFeesByStudentId
      summary: Return fees applicable for student
      parameters:
        - name: studentId
          in: path
          description: Unique StudentId i.e Roll-number
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StudentFeeDetails'

  '/student/{studentId}/fee:payment':
    post:
      operationId: initiateFeePayment
      summary: Initiate a payment
      parameters:
        - name: studentId
          in: path
          description: Unique StudentId i.e Roll-number
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/StudentFeePaymentRequest"
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StudentFeePaymentResponse'

  '/student/{studentId}/fee/payment/{paymentReference}:status':
    get:
      operationId: getFeePaymentStatus
      summary: Initiate a payment
      parameters:
        - name: studentId
          in: path
          description: Unique StudentId i.e Roll-number
          required: true
          schema:
            type: string
        - name: paymentReference
          in: path
          description: Unique paymentReference
          required: true
          schema:
            type: string
      responses:
        '200':
          description: "Student Fee Payment Status"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StudentFeeDetails'

  '/student/{studentId}/fee:payment-status':
    put:
      operationId: feePaymentStatus
      summary: Record payment-status sent by payment-service
      parameters:
        - name: studentId
          in: path
          description: Unique StudentId i.e Roll-number
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/StudentFeePaymentStatusRequest"
      responses:
        '201':
          description: Created

  '/student/{studentId}/payment/{paymentReference}/fee:receipt':
    get:
      operationId: getFeeReceiptByStudentId
      summary: Return fee receipt for student
      parameters:
        - name: studentId
          in: path
          description: Unique StudentId i.e Roll-number
          required: true
          schema:
            type: string
        - name: paymentReference
          in: path
          description: Unique paymentReference
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StudentFeeReceipt'

components:
  schemas:
    StudentFeeReceipt:
      type: object
      properties:
        dateTime:
          type: string
          format: date-time
        studentName:
          type: string
        studentId:
          type: string
        referenceNumber:
          type: string
        cardNumber:
          type: string
        cardType:
          type: string
        totalAmount:
          type: number
        paymentDetails:
          type: 'array'
          items:
            $ref: "#/components/schemas/FeePaymentDetails"

    FeePaymentDetails:
      type: object
      properties:
        feeType:
          type: string
        feeAmount:
          type: number


    StudentFeePaymentStatusRequest:
      type: object
      properties:
        status:
          type: string
        paymentReference:
          type: string

    StudentFeePaymentRequest:
      type: object
      properties:
        totalAmount:
          type: number
        cardNumber:
          type: string
        cardType:
          type: string
        feeDetails:
          type: "array"
          items:
            $ref: "#/components/schemas/FeePayment"


    StudentFeeDetails:
      type: object
      properties:
        studentName:
          type: string
        studentId:
          type: string
        totalPendingAmount:
          type: number
        fees:
          type: "array"
          items:
            $ref: '#/components/schemas/Fee'

    FeePayment:
      type: object
      properties:
        feeType:
          type: string
        feeAmount:
          type: number
        customAmount:
          type: number

    Fee:
      type: object
      properties:
        feeType:
          type: string
        feeAmount:
          type: number

    StudentFeePaymentResponse:
      type: object
      properties:
        studentId:
          type: string
        paymentReference:
          type: string
        paymentStatus:
          type: string

