openapi: 3.0.1
info:
  title: Fee API
  description: API to support fee details
  version: ${proect.version}

paths:
  /fee/{grade}:
    get:
      tags:
        - Get Fees by Grade
      operationId: getFeesByGrade
      summary: "Returns fees by Grade"
      parameters:
        - name: grade
          in: path
          description: Grade
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FeeDetails"
  /fee:
    post:
      tags:
        - Add Fees by Grade
      operationId: addFeesBygrade
      summary: "Add fees by Grade"
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FeeDetails"

components:
  schemas:
    FeeDetails:
      type: "object"
      title: ""
      properties:
        data:
          type: "array"
          items:
            $ref: "#/components/schemas/Fee"

    Fee:
      type: "object"
      properties:
        feeType:
          type: "string"
        feeAmount:
          type: "number"